### ISSUE TITLE
Game Mechanic

### ISSUE THREAD

**Issue by SeanDunford** [SeanDunford/phaser#2]
This is up for discussion first. Then implementation. 

Ideas 
- Fuck it just do a fighting game as hacky as we can. Maybe the user can spam defend whatever it's straightforward 
- Rock paper scissors style priorty 
- Turn based 
- Real time 
- AI? Just spam random shit from enemy. Math.random() and then use that value to execute one of the 3 moves.

**Comment by dozel** [comment]
Ok, so from what we discussed on Friday the mechanic is:
- Real Time
- Cooldown periods for the three options
- Vulnerable seconds for each option animation will determine who gets hit
-  If by chance the two players hit at the same damn time, coin toss - Math.random()
