### ISSUE TITLE
Add animations into project

### ISSUE THREAD

**Issue by SeanDunford** [SeanDunford/phaser#3]
Not sure which of these has been animated yet. @dozel ? 

@drake 
- [x] idle
- [ ]  punch 
- [ ] defend
- [ ] special
- [ ] hit

@meek 
- [x] idle
- [ ] punch 
- [ ] defend
- [ ] special
- [ ] hit

@buttons
- [ ] punch
- [ ] special
- [ ] defend

@audience-crowd
- [ ] Nicki Minaj
- [ ] Kanye?
  You know this better than I do. I trust you @SeanDunford

**Comment by dozel** [comment]
Only Drake's punch. I'll make the spritesheet.

**Comment by SeanDunford** [comment]
@dozel just keep crowd to nikki for now.

**Comment by dozel** [comment]
@SeanDunford yeah of course, I'm just putting the names down for future reference.
