### ISSUE TITLE
Attach button mechanics to the.... buttons. 

### ISSUE THREAD

**Issue by SeanDunford** [SeanDunford/phaser#4]
Right now we have 3 graphically placed sprites but they aren't wired up to do anything.

**Comment by SeanDunford** [comment]
Got them to console.log. Need them to trigger animations and decrement health.

**Comment by dozel** [comment]
They also need animations.

**Comment by SeanDunford** [comment]
I was just going to look at how to do it with like a shader or something. Worth researching. How to make them depress.
